-- MySQL Script generated by MySQL Workbench
-- 04/03/17 15:58:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID_User` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Registered` DATETIME NOT NULL,
  PRIMARY KEY (`ID_User`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `ID_Image` INT NOT NULL AUTO_INCREMENT,
  `ID_Author` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Path` VARCHAR(400) NOT NULL,
  `Created` DATETIME NOT NULL,
  `Updated` DATETIME NOT NULL,
  PRIMARY KEY (`ID_Image`),
  INDEX `fk_Image_User_idx` (`ID_Author` ASC),
  CONSTRAINT `fk_Image_User`
    FOREIGN KEY (`ID_Author`)
    REFERENCES `mydb`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `Name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `ID_Comment` INT NOT NULL AUTO_INCREMENT,
  `ID_Image` INT NOT NULL,
  `ID_Author` INT NOT NULL,
  `Message` VARCHAR(100) NOT NULL,
  `Created` DATETIME NOT NULL,
  `Updated` DATETIME NOT NULL,
  PRIMARY KEY (`ID_Comment`),
  INDEX `fk_Comment_User1_idx` (`ID_Author` ASC),
  INDEX `fk_Comment_Image1_idx` (`ID_Image` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`ID_Author`)
    REFERENCES `mydb`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Image1`
    FOREIGN KEY (`ID_Image`)
    REFERENCES `mydb`.`Image` (`ID_Image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image_Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Image_Rating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Image_Rating` (
  `ID_Image` INT NOT NULL,
  `ID_User` INT NOT NULL,
  `Rating` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_Image`, `ID_User`),
  INDEX `fk_Image_has_User_User1_idx` (`ID_User` ASC),
  INDEX `fk_Image_has_User_Image1_idx` (`ID_Image` ASC),
  CONSTRAINT `fk_Image_has_User_Image1`
    FOREIGN KEY (`ID_Image`)
    REFERENCES `mydb`.`Image` (`ID_Image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Image_has_User_User1`
    FOREIGN KEY (`ID_User`)
    REFERENCES `mydb`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment_Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comment_Rating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comment_Rating` (
  `ID_Comment` INT NOT NULL,
  `ID_User` INT NOT NULL,
  `Rating` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_Comment`, `ID_User`),
  INDEX `fk_User_has_Comment_Comment1_idx` (`ID_Comment` ASC),
  INDEX `fk_User_has_Comment_User1_idx` (`ID_User` ASC),
  CONSTRAINT `fk_User_has_Comment_User1`
    FOREIGN KEY (`ID_User`)
    REFERENCES `mydb`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Comment_Comment1`
    FOREIGN KEY (`ID_Comment`)
    REFERENCES `mydb`.`Comment` (`ID_Comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Image_Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Image_Tag` (
  `ID_Image` INT NOT NULL,
  `Name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID_Image`, `Name`),
  INDEX `fk_Image_has_Tag_Tag1_idx` (`Name` ASC),
  INDEX `fk_Image_has_Tag_Image1_idx` (`ID_Image` ASC),
  CONSTRAINT `fk_Image_has_Tag_Image1`
    FOREIGN KEY (`ID_Image`)
    REFERENCES `mydb`.`Image` (`ID_Image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Image_has_Tag_Tag1`
    FOREIGN KEY (`Name`)
    REFERENCES `mydb`.`Tag` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
