Create table User (
	ID_User Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	Username Varchar(45) NOT NULL,
	Registered Datetime NOT NULL,
	Primary Key (ID_User)
);

Create table Image (
	ID_Image Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	ID_Author Int NOT NULL,
	Name Varchar(45) NOT NULL,
	Path Varchar(400) NOT NULL,
	Created Datetime NOT NULL,
	Updated Datetime NOT NULL,
	Primary Key (ID_Image)
);

Create table Tag (
	Name Varchar(16) NOT NULL,
	Primary Key (Name)
);

Create table Comment (
	ID_Comment Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	ID_Image Int NOT NULL,
	ID_Author Int NOT NULL,
	Message Varchar(100) NOT NULL,
	Created Datetime NOT NULL,
	Updated Datetime NOT NULL,
	Primary Key (ID_Comment)
);

Create table Image_Rating (
	ID_Image Int NOT NULL,
	ID_User Int NOT NULL,
	Rating BOOLEAN NOT NULL,
	Primary Key (ID_Image,ID_User)
);

Create table Comment_Rating (
	ID_Comment Int NOT NULL,
	ID_User Int NOT NULL,
	Rating BOOLEAN NOT NULL,
	Primary Key (ID_Comment,ID_User)
);

Create table Image_Tag (
	ID_Image Int NOT NULL,
	Name Varchar(16) NOT NULL,
	Primary Key (ID_Image,Name)
);

Alter table Image add Foreign Key (ID_Author) references User (ID_User) on delete  restrict on update  restrict;

Alter table Image_Rating add Foreign Key (ID_Image) references Image (ID_Image) on delete  restrict on update  restrict;
Alter table Image_Rating add Foreign Key (ID_User) references User (ID_User) on delete  restrict on update  restrict;

Alter table Image_Tag add Foreign Key (ID_Image) references Image (ID_Image) on delete  restrict on update  restrict;
Alter table Image_Tag add Foreign Key (Name) references Tag (Name) on delete  restrict on update  restrict;

Alter table Comment add Foreign Key (ID_Image) references Image (ID_Image) on delete  restrict on update  restrict;
Alter table Comment add Foreign Key (ID_Author) references User (ID_User) on delete  restrict on update  restrict;

Alter table Comment_Rating add Foreign Key (ID_Comment) references Comment (ID_Comment) on delete  restrict on update  restrict;
Alter table Comment_Rating add Foreign Key (ID_User) references User (ID_User) on delete  restrict on update  restrict;

Create trigger insert_User
Before insert on User
	Referencing NEW ROW AS new
For each row
SET new.Registered=NOW()

Create trigger insert_Image
Before insert on Image
	Referencing NEW ROW AS new
For each row
SET new.Created=NOW()

Create trigger insert_Comment
Before insert on Comment
	Referencing NEW ROW AS new
For each row
SET new.Created=NOW()

Create trigger update_Image
Before update on Image
Referencing NEW ROW AS new
For each row
SET new.Updated=NOW()

Create trigger update_Comment
Before update on Comment
Referencing NEW ROW AS new
For each row
SET new.Updated=NOW()